### ISSUE TITLE
🔧 Add Comprehensive Pre-commit Hooks

### ISSUE THREAD

**Issue by ARYAN-NIKNEZHAD** [ahmedaljawahiry/django-admin-site-search#30]
### Overview

I propose updating the current `.pre-commit-config.yaml` to include a more comprehensive set of pre-commit hooks. This update will help automate various checks and formatting tasks, thereby improving the overall quality and consistency of the codebase.

### Current Configuration

The existing `.pre-commit-config.yaml` contains the following repositories and hooks:

```yaml
repos:
- repo: https://github.com/ambv/black
  rev: 23.1.0
  hooks:
  - id: black
    language_version: python3.10
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args:
      - "--profile"
      - "black"
- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.7.0
  hooks:
  - id: djlint-django
    args:
      - "--reformat"
      - "--quiet"
```

### Key Enhancements:
1. Code Formatting: Tools like black, isort, and docformatter will automatically format code, ensuring a consistent style across the project.
2. Linting and Static Analysis: Integrating ruff, pylint, and bandit will help catch code issues early, including potential security vulnerabilities.
3. Configuration File Formatting: Hooks for formatting pyproject.toml and .ini files will maintain clean and standardized configuration files.
4. Documentation: Using blacken-docs and rstcheck ensures that our documentation is well-formatted and free of errors.
5. Custom Hooks: Implementing local hooks for running tests and linting before commits ensures that code quality checks are enforced consistently.
